#!/usr/bin/perl
use 5.020;
use Text::HTML::Turndown;

my $t = Text::HTML::Turndown->new();

say $t->turndown( <<'HTML' );
<h1>Hello world!</h1>
HTML

say $t->turndown( <<'HTML' );
<h2>Hello world!</h2>
HTML
